---
driver:
  name: molecule-proxmox
  options:
    proxmox_secrets: $HOME/.molecule/proxmox-secrets.yml

platforms:
  - name: molecule-proxmox-9.1
    template_name: proxmox-9.1-tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
    ANSIBLE_ROLES_PATH: "../../roles"
  lint:
    name: "ansible-lint"
