---
driver:
  name: molecule-proxmox
  options:
    proxmox_secrets: $HOME/.molecule/proxmox-secrets.yml

platforms:
  - name: molecule-proxmox-test
    template_name: proxmox-9-tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 2
    ANSIBLE_ROLES_PATH: "../../roles"
