__accounts_histsize: 10000
__accounts_histfilesize: 10000
__accounts_histtimeformat: "%d.%m.%Y %H:%M:%S - "
__accounts_histcontrol: "ignoreboth:erasedups"
__accounts_prompt_command: "history -a"
